
version: "3.8"
x-logging:
  &armm-logging
  options:
    max-size: '12m'
    max-file: '5'
  driver: json-file

services:
  integration_orchestrator:
    image: us-central1-docker.pkg.dev/armm-sandbox/hem-armm/integration-orchestrator:latest
    env_file:
      - .env
    ports:
      - "8089:8080"
    depends_on:
      - database
    security_opt:
      - no-new-privileges:true
    read_only: true

  database:
    image: us-central1-docker.pkg.dev/armm-sandbox/hem-armm/hem-postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: armm
      POSTGRES_PASSWORD: armm
      POSTGRES_DB: armm
    volumes:
      - database_data:/var/lib/postgresql/data
    logging: *armm-logging
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    security_opt:
      - no-new-privileges:true
    read_only: true

volumes:
  database_data:
    driver: local
